
server:
  port: 8080

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  application:
    name: app


spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.DerbyDialect


