
server:
  port: 8080

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  application:
    name: topic-service


spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.DerbyDialect
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
          defaultZone: http://localhost:8083/eureka/




